/*
 * This file was automatically generated by EvoSuite
 * Mon May 27 07:47:01 CST 2019
 */

package app.server.vo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class LikeVOTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      likeVO0.setUsername("V");
      String string0 = likeVO0.getUsername();
      assertEquals("V", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      likeVO0.setCommentId(1);
      int int0 = likeVO0.getCommentId();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      likeVO0.setCommentId((-1));
      int int0 = likeVO0.getCommentId();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      int int0 = likeVO0.getCommentId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      String string0 = likeVO0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LikeVO likeVO0 = new LikeVO();
      likeVO0.setUsername("");
      String string0 = likeVO0.getUsername();
      assertEquals("", string0);
  }
}
