/*
 * This file was automatically generated by EvoSuite
 * Mon May 27 07:47:13 CST 2019
 */

package app.server.vo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class StudentVOTest{

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setUsername("y");
      String string0 = studentVO0.getUsername();
      assertEquals("y", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setUsername("");
      String string0 = studentVO0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setStudentNumber("u");
      String string0 = studentVO0.getStudentNumber();
      assertEquals("u", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setStudentNumber("");
      String string0 = studentVO0.getStudentNumber();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setSchool("R");
      String string0 = studentVO0.getSchool();
      assertEquals("R", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setPassword("u");
      String string0 = studentVO0.getPassword();
      assertEquals("u", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setMajor("a");
      String string0 = studentVO0.getMajor();
      assertEquals("a", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setCollege("K");
      String string0 = studentVO0.getCollege();
      assertEquals("K", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getStudentNumber();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getCollege();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setCollege("");
      String string0 = studentVO0.getCollege();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getMajor();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setPassword("");
      String string0 = studentVO0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setSchool("");
      String string0 = studentVO0.getSchool();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      String string0 = studentVO0.getSchool();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StudentVO studentVO0 = new StudentVO();
      studentVO0.setMajor("");
      String string0 = studentVO0.getMajor();
      assertEquals("", string0);
  }
}
