/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 19:56:16 CST 2019
 */

package app.server.bean;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Collect_ESTest extends Collect_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setID(1);
      int int0 = collect0.getID();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setID((-1));
      int int0 = collect0.getID();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setUsername("y");
      String string0 = collect0.getUsername();
      assertEquals("y", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setCourseId("y");
      String string0 = collect0.getCourseId();
      assertEquals("y", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setCourseId("");
      String string0 = collect0.getCourseId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Collect collect0 = new Collect();
      int int0 = collect0.getID();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Collect collect0 = new Collect();
      String string0 = collect0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Collect collect0 = new Collect();
      collect0.setUsername("");
      String string0 = collect0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Collect collect0 = new Collect();
      String string0 = collect0.getCourseId();
      assertNull(string0);
  }
}
