/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 09:08:17 GMT 2019
 */

package app.server.util;

import org.junit.Test;
import static org.junit.Assert.*;
import app.server.util.LoggerUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoggerUtil_ESTest extends LoggerUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoggerUtil loggerUtil0 = LoggerUtil.loggerUtil;
      loggerUtil0.logWarn("o");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoggerUtil loggerUtil0 = LoggerUtil.loggerUtil;
      loggerUtil0.logErr("o");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoggerUtil loggerUtil0 = LoggerUtil.loggerUtil;
      loggerUtil0.logInfo("o");
  }
}
