/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 20:00:20 CST 2019
 */

package app.server.impl;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

import app.server.service.impl.StudentImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class StudentImpl_ESTest extends StudentImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StudentImpl studentImpl0 = new StudentImpl();
      // Undeclared exception!
      try { 
        studentImpl0.updateStudentPassword("", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // main/java/dao/StudentDAO
         //
         verifyException("service.impl.StudentImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StudentImpl studentImpl0 = new StudentImpl();
      // Undeclared exception!
      try { 
        studentImpl0.updateStudentInfo("", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // main/java/dao/StudentDAO
         //
         verifyException("service.impl.StudentImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StudentImpl studentImpl0 = new StudentImpl();
      // Undeclared exception!
      try { 
        studentImpl0.register("", "", "", "", "", "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // main/java/dao/StudentDAO
         //
         verifyException("service.impl.StudentImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StudentImpl studentImpl0 = new StudentImpl();
      // Undeclared exception!
      try { 
        studentImpl0.login("", "");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // main/java/dao/StudentDAO
         //
         verifyException("service.impl.StudentImpl", e);
      }
  }
}
